import {createClient} from '@supabase/supabase-js';
import {NextRequest,NextResponse} from 'next/server';
import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
export const runtime='nodejs';export const dynamic='force-dynamic';
const SOL='FA440726QJC05',BUCKET='scott-afb-sitewalk';
const sections:Record<string,string>={access:'Arrival / Base Access',carrier:'Carrier / Demarc',mdf:'B1820 MDF',fiber:'Interbuilding Fiber',idf:'Six Attic IDFs',wifi:'Wi-Fi / AP Survey',cable:'Horizontal Cabling',power:'Power / Grounding',ops:'Construction / Operations',sla:'Maintenance / SLA',q:'Government Questions',evidence:'Evidence / Closeout'};
const label=(id:string)=>{if(id.startsWith('idf'))return sections.idf;for(const k of Object.keys(sections))if(id.startsWith(k))return sections[k];return 'Other'};
const safe=(v:unknown)=>String(v??'').replace(/[\u2018\u2019]/g,"'").replace(/[\u201C\u201D]/g,'"').replace(/[\u2013\u2014]/g,'-').replace(/[^\x09\x0A\x0D\x20-\x7E]/g,'');
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)return null;return createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}})}
export async function POST(req:NextRequest){const s=db();if(!s)return NextResponse.json({error:'Report backend not configured.'},{status:503});try{const body=await req.json().catch(()=>({}));let state=body.state;const deviceId=String(body.deviceId||'');if(!state){let q=s.from('sitewalk_sessions').select('state').eq('solicitation',SOL).order('server_updated_at',{ascending:false}).limit(1);if(deviceId)q=q.eq('device_id',deviceId);const {data,error}=await q;if(error)throw error;state=data?.[0]?.state}if(!state)return NextResponse.json({error:'No site-walk data found.'},{status:404});
 const {data:photos,error:pe}=await s.from('sitewalk_photos').select('*').eq('solicitation',SOL).order('captured_at',{ascending:true});if(pe)throw pe;
 const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);const navy=rgb(.043,.122,.227),gray=rgb(.36,.42,.49),light=rgb(.94,.96,.98),red=rgb(.66,.10,.07),green=rgb(.07,.39,.16);const W=612,H=792,M=46;let page=pdf.addPage([W,H]),y=H-M;
 const newPage=()=>{page=pdf.addPage([W,H]);y=H-M;footer()};const footer=()=>{page.drawLine({start:{x:M,y:28},end:{x:W-M,y:28},thickness:.5,color:rgb(.8,.83,.87)});page.drawText(`ODISCOM | Scott AFB | ${SOL}`,{x:M,y:15,size:7,font:regular,color:gray});};
 const ensure=(h:number)=>{if(y-h<42)newPage()};const wrap=(text:string,max:number,size:number,font=regular)=>{const words=safe(text).split(/\s+/),lines:string[]=[];let line='';for(const w of words){const t=line?line+' '+w:w;if(font.widthOfTextAtSize(t,size)<=max)line=t;else{if(line)lines.push(line);line=w}}if(line)lines.push(line);return lines};const text=(t:string,x:number,size=9,color=rgb(.08,.13,.22),max=W-M-x,font=regular)=>{const ls=wrap(t,max,size,font);ensure(ls.length*(size+3)+3);for(const l of ls){page.drawText(l,{x,y,size,font,color});y-=size+3}return ls.length};
 footer();page.drawRectangle({x:0,y:H-150,width:W,height:150,color:navy});page.drawText('ODISCOM',{x:M,y:H-72,size:15,font:bold,color:rgb(1,1,1)});page.drawText('SCOTT AFB WI-FI SITE WALK REPORT',{x:M,y:H-103,size:22,font:bold,color:rgb(1,1,1)});page.drawText(SOL,{x:M,y:H-126,size:11,font:regular,color:rgb(.83,.89,.96)});y=H-180;
 const completed=Object.values(state.done||{}).filter(Boolean).length,issues=Object.values(state.issue||{}).filter(Boolean).length;page.drawText('FIELD REPORT SUMMARY',{x:M,y,size:12,font:bold,color:navy});y-=20;const cards=[['Field Representative',safe(state.attendee||'Not entered')],['Building',safe(state.building||'All Buildings')],['Completed Items',String(completed)],['Flagged Issues',String(issues)],['Cloud Photos',String((photos||[]).length)],['Generated',new Date().toLocaleString('en-US',{timeZone:'America/Chicago'})+' CT']];for(let i=0;i<cards.length;i++){const col=i%2,row=Math.floor(i/2),x=M+col*260,yy=y-row*54;page.drawRectangle({x,y:yy-38,width:244,height:44,color:light,borderColor:rgb(.84,.87,.9),borderWidth:.5});page.drawText(cards[i][0],{x:x+10,y:yy-14,size:7,font:bold,color:gray});page.drawText(cards[i][1],{x:x+10,y:yy-29,size:10,font:bold,color:navy})}y-=172;
 if(state.general){page.drawText('GENERAL FIELD NOTES',{x:M,y,size:11,font:bold,color:navy});y-=17;text(state.general,M,9,rgb(.08,.13,.22),W-2*M);y-=8}
 const ids=Array.from(new Set([...Object.keys(state.done||{}),...Object.keys(state.issue||{}),...Object.keys(state.notes||{})])).filter(Boolean);for(const sec of Object.values(sections)){const secIds=ids.filter(id=>label(id)===sec);if(!secIds.length)continue;ensure(44);page.drawRectangle({x:M,y:y-20,width:W-2*M,height:24,color:navy});page.drawText(sec.toUpperCase(),{x:M+10,y:y-13,size:10,font:bold,color:rgb(1,1,1)});y-=34;for(const id of secIds){const done=!!state.done?.[id],issue=!!state.issue?.[id],note=safe(state.notes?.[id]||'');ensure(42);page.drawCircle({x:M+6,y:y-4,size:4,color:done?green:rgb(.72,.75,.78)});page.drawText(issue?'ISSUE':'FIELD ITEM',{x:M+18,y:y-7,size:7,font:bold,color:issue?red:gray});y-=16;if(note){text(note,M+18,9,issue?red:rgb(.08,.13,.22),W-M-(M+18));}else{text(`Item ${id}: ${done?'Completed':'Not completed'}${issue?' - flagged for follow-up':''}`,M+18,8,gray,W-M-(M+18));}y-=6}}
 if((photos||[]).length){ensure(45);page.drawRectangle({x:M,y:y-20,width:W-2*M,height:24,color:navy});page.drawText('PHOTO LOG',{x:M+10,y:y-13,size:10,font:bold,color:rgb(1,1,1)});y-=34;let n=0;for(const p of photos||[]){n++;ensure(150);let embedded:any=null;try{const {data}=await s.storage.from(BUCKET).download(p.storage_path);if(data){const bytes=new Uint8Array(await data.arrayBuffer());if((p.mime_type||'').includes('png'))embedded=await pdf.embedPng(bytes);else if((p.mime_type||'').includes('jpeg')||(p.mime_type||'').includes('jpg'))embedded=await pdf.embedJpg(bytes)}}catch{}if(embedded){const maxW=240,maxH=125,scale=Math.min(maxW/embedded.width,maxH/embedded.height,1);const iw=embedded.width*scale,ih=embedded.height*scale;page.drawImage(embedded,{x:M,y:y-ih,width:iw,height:ih});const tx=M+iw+14;page.drawText(`PHOTO ${n}`,{x:tx,y:y-10,size:8,font:bold,color:navy});let yy=y-25;for(const l of wrap(`${safe(p.building)} | ${safe(p.item_id)}`,W-M-tx,8)){page.drawText(l,{x:tx,y:yy,size:8,font:bold,color:rgb(.08,.13,.22)});yy-=11}for(const l of wrap(`${new Date(p.captured_at||p.uploaded_at).toLocaleString('en-US',{timeZone:'America/Chicago'})} CT`,W-M-tx,7)){page.drawText(l,{x:tx,y:yy,size:7,font:regular,color:gray});yy-=10}y-=Math.max(ih,80)+18}else{text(`Photo ${n}: ${safe(p.building)} | ${safe(p.item_id)} | ${safe(p.original_name)}`,M,8,gray,W-2*M);y-=6}}}
 const pages=pdf.getPages();pages.forEach((p,i)=>p.drawText(`Page ${i+1} of ${pages.length}`,{x:W-M-55,y:15,size:7,font:regular,color:gray}));const bytes=await pdf.save();return new NextResponse(Buffer.from(bytes),{headers:{'content-type':'application/pdf','content-disposition':`attachment; filename="Scott_AFB_Site_Walk_Report_${new Date().toISOString().slice(0,10)}.pdf"`,'cache-control':'no-store'}})}catch(e){console.error('PDF report failed',e);return NextResponse.json({error:e instanceof Error?e.message:'Could not generate PDF.'},{status:500})}}
