'use client';
import {useState} from 'react';
type Photo={id:string;attendee:string;building:string;item_id:string;original_name:string;mime_type:string;size_bytes:number;captured_at:string;uploaded_at:string;url:string|null};
export default function CloudPhotoGallery(){
 const [open,setOpen]=useState(false),[loading,setLoading]=useState(false),[photos,setPhotos]=useState<Photo[]>([]),[error,setError]=useState(''),[selected,setSelected]=useState<Set<string>>(new Set()),[deleting,setDeleting]=useState(false);
 async function load(){setOpen(true);setLoading(true);setError('');try{const r=await fetch('/api/sitewalk/scott-afb/photos',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'Could not retrieve photos');setPhotos(j.photos||[]);setSelected(new Set())}catch(e){setError(e instanceof Error?e.message:'Could not retrieve photos')}finally{setLoading(false)}}
 async function remove(ids:string[]){if(!ids.length)return;if(!confirm(`Permanently delete ${ids.length===1?'this photo':`${ids.length} photos`} from Odiscom cloud storage? This cannot be undone.`))return;setDeleting(true);setError('');try{const r=await fetch('/api/sitewalk/scott-afb/photos',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({ids})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Delete failed');setPhotos(p=>p.filter(x=>!ids.includes(x.id)));setSelected(s=>{const n=new Set(s);ids.forEach(id=>n.delete(id));return n})}catch(e){setError(e instanceof Error?e.message:'Could not delete photos')}finally{setDeleting(false)}}
 function toggle(id:string){setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
 return <><button onClick={load} style={{position:'fixed',left:12,bottom:68,zIndex:9998,border:0,borderRadius:12,padding:'12px 16px',background:'#0b1f3a',color:'#fff',fontWeight:700,fontSize:15,boxShadow:'0 4px 18px #0004'}}>📷 Cloud Photos</button>{open&&<div style={{position:'fixed',inset:0,zIndex:10000,background:'#0009',padding:12,overflow:'auto'}} onClick={()=>setOpen(false)}><div onClick={e=>e.stopPropagation()} style={{maxWidth:900,margin:'30px auto',background:'#f7f9fc',borderRadius:16,padding:16,color:'#10213a'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:14}}><div><b style={{fontSize:22}}>📷 Scott AFB Cloud Photos</b><div style={{fontSize:13,opacity:.7}}>FA440726QJC05 · private Odiscom storage</div></div><button onClick={()=>setOpen(false)} style={{fontSize:24,border:0,background:'transparent'}}>✕</button></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:12}}><button onClick={load} style={{padding:'8px 12px'}}>↻ Refresh</button>{selected.size>0&&<button disabled={deleting} onClick={()=>remove(Array.from(selected))} style={{padding:'8px 12px',background:'#a52318',color:'#fff',border:0,borderRadius:5,fontWeight:700}}>🗑 Delete Selected ({selected.size})</button>}</div>{loading&&<p>Retrieving cloud photos…</p>}{error&&<p style={{color:'#9b1c14'}}>{error}</p>}{!loading&&!error&&photos.length===0&&<p>No cloud photos yet.</p>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{photos.map(p=><div key={p.id} style={{background:'#fff',border:selected.has(p.id)?'2px solid #0b1f3a':'1px solid #d9e0e8',borderRadius:12,overflow:'hidden'}}><div style={{position:'relative'}}><a href={p.url||'#'} target="_blank" rel="noreferrer">{p.url&&<img src={p.url} alt={p.original_name||'Site walk photo'} style={{width:'100%',height:180,objectFit:'cover',display:'block'}}/>}</a><label style={{position:'absolute',top:8,left:8,background:'#fffd',padding:'6px 8px',borderRadius:7,fontWeight:700}}><input type="checkbox" checked={selected.has(p.id)} onChange={()=>toggle(p.id)}/> Select</label></div><div style={{padding:10,fontSize:13}}><b>{p.building||'All Buildings'} · {p.item_id}</b><div>{new Date(p.captured_at||p.uploaded_at).toLocaleString()}</div>{p.attendee&&<div>Field rep: {p.attendee}</div>}<div style={{opacity:.65,marginTop:3}}>{p.original_name} · {(Number(p.size_bytes||0)/1048576).toFixed(1)} MB</div><button disabled={deleting} onClick={()=>remove([p.id])} style={{marginTop:9,width:'100%',padding:8,border:'1px solid #b42318',borderRadius:7,background:'#fff',color:'#a52318',fontWeight:700}}>🗑 Delete Photo</button></div></div>)}</div></div></div>}</>
}
