'use client';
import {useEffect,useRef,useState} from 'react';
const storageKey='odiscom-scott-afb-sitewalk-v3';const deviceKey='odiscom-scott-afb-device-id';
export default function LiveStateSync(){const [msg,setMsg]=useState('Starting cloud backup…');const [bad,setBad]=useState(false);const [last,setLast]=useState('');const lastPayload=useRef('');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{let deviceId=localStorage.getItem(deviceKey);if(!deviceId){deviceId=crypto.randomUUID();localStorage.setItem(deviceKey,deviceId)}
  const sync=async()=>{const raw=localStorage.getItem(storageKey);if(!raw)return;let state;try{state=JSON.parse(raw)}catch{return}const payload=JSON.stringify(state);if(payload===lastPayload.current)return;setMsg(navigator.onLine?'Saving field data…':'Offline — changes saved on phone');setBad(!navigator.onLine);if(!navigator.onLine)return;try{const r=await fetch('/api/sitewalk/scott-afb/state',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({deviceId,state,clientUpdatedAt:new Date().toISOString()})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`Sync failed (${r.status})`);lastPayload.current=payload;const t=new Date(b.serverUpdatedAt||Date.now()).toLocaleTimeString([], {hour:'numeric',minute:'2-digit',second:'2-digit'});setLast(t);setBad(false);setMsg('✓ All field data saved to cloud')}catch(e){setBad(true);setMsg(`⚠ Cloud save pending — ${e instanceof Error?e.message:'retrying'}`)}};
  const schedule=()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(sync,1200)};
  const storage=(e:StorageEvent)=>{if(e.key===storageKey)schedule()};window.addEventListener('storage',storage);window.addEventListener('online',schedule);window.addEventListener('offline',()=>{setBad(true);setMsg('Offline — changes saved on phone')});
  const poll=setInterval(()=>{const raw=localStorage.getItem(storageKey)||'';if(raw!==lastPayload.current)schedule()},1500);schedule();return()=>{window.removeEventListener('storage',storage);clearInterval(poll);if(timer.current)clearTimeout(timer.current)}},[]);
 return <div style={{position:'fixed',left:12,top:12,zIndex:9999,maxWidth:320,padding:'9px 11px',borderRadius:11,background:bad?'#8f1d14':'#116329',color:'#fff',boxShadow:'0 4px 18px #0004',fontFamily:'Arial,sans-serif',fontSize:12}}><b>☁ Cloud Data</b><div style={{marginTop:2}}>{msg}</div>{last&&<div style={{fontSize:10,opacity:.85,marginTop:2}}>Last server save: {last}</div>}</div>}
